name: art_vibes1
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  firebase_data_connect: ^0.1.1
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  url_launcher: ^6.0.20
  firebase_storage: ^12.2.3
  google_maps_flutter: ^2.2.5 # Add this line for Google Maps
  intl: ^0.19.0 # or the required version
  shared_preferences: ^2.0.15  # Add this line (or latest version)
  file_picker: ^8.1.3
  image_picker: ^1.1.2
  firebase_core: ^3.6.0
  firebase_app_check: ^0.3.1+4  # Or another compatible version
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.0
  flutter_pdfview: ^1.0.0
  geolocator: ^9.0.1
  provider: ^6.0.0



  





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Art_vibes_Logo.png
    - assets/images/Logo 1.png
    - assets/images/image1.png
    - assets/images/image2.png
    - assets/images/image3.png
    - assets/images/image4.png
    - assets/images/image5.png
    - assets/images/image6.png
    - assets/images/image7.png
    - assets/images/image8.png
    - assets/images/image9.png
    - assets/images/image10.png
    - assets/images/image11.png
    - assets/images/image12.png
    - assets/images/image13.png
    - assets/images/image14.png
    - assets/images/image15.png
    - assets/images/image16.png
    - assets/images/image17.png
    - assets/images/image18.png
    - assets/images/welcome.png
